### ISSUE TITLE
Problematic control logic around peer count

### ISSUE THREAD

**Issue by rswarthout** [N3TC4T/rippled-agent#1]
My validator has 5 peers, configured via peer_private = 1 and ips_fixed. The configuration I am running was put into place with the help of talking to @alloynetworks. The lines of code that need to be adjusted are https://github.com/N3TC4T/valmond/blob/master/src/checks/validation.cpp#L96-L110. 

I am not knowledgeable enough to know why 7 might have been chosen. I would be curious in knowing why 5 peers would be deemed non-optimal. My suggestion for a change is the following.

```
        if (serverInfo["peers"] > 7)
        {
            peersCheck["exit_code"] = 0;
            peersCheck["output"] = "Check Peer count OK: Peer count is greater than 7";
        }
        else if (serverInfo["peers"] <= 7 && serverInfo["peers"] != 0)
        {
            peersCheck["exit_code"] = 1;
            peersCheck["output"] = "Check Peer count WARNING: Peer count is less than or equal to 7";
        }
        else
        {
            peersCheck["exit_code"] = 2;
            peersCheck["output"] = "Check Peer count CRITICAL: Peer count is zero.";
        }
```

**Comment by N3TC4T** [comment]
Hi Robert

thanks for mentioning this, actually I'm aware of this issue and I will publish an update for it :+1:
